
---@class Camera : DynamicInstance
---@field Distance number
---@field FOV number
---@field FastFlySpeed number
---@field FlySpeed number
---@field FollowLerp boolean
---@field FreeLookSensitivity number
---@field HorizontalSpeed number
---@field IsFirstPerson boolean
---@field LerpSpeed number
---@field MaxDistance number
---@field MinDistance number
---@field Mode CameraMode
---@field Orthographic boolean
---@field OrthographicSize number
---@field PositionOffset Vector3
---@field RotationOffset Vector3
---@field ScrollSensitivity number
---@field VerticalSpeed number
---@field ClipThroughWalls boolean
---@field SensitivityMultiplier number
